---
title: "UN report about GDP and Life Exp"
author: "Jiucheng"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r packages}
library(tidyverse)
```
```{r}
"This report was prepared to the attention of the United Nations. It analyzes the relationship between a country's GDP, its life expectancy and CO2 emissions. Our goal is to determine to what degree a country’s economic strength or weakness may be related to its public health status and impact on climate pollution. We hypothesize that both life expectancy and CO2 emissions increase with a country's GDP."
```

```{r data}
gapminder_1997 <- read_csv("data/gapminder_1997.csv")
```
```{r gdp_lifeexp_1997}
  ggplot(data = gapminder_1997) +
  aes(x = gdpPercap, y = lifeExp, color=continent, size=pop/1000000) +
  geom_point() +
  labs(x = "GDP per Capita", y = "Life Expectancy", title = "Do people in richer countries live longer?", 
  size = "Population (in millions)")
```











